# basic options
title: rupertarnold.com
author: Rupert Arnold Hoffschmidt
email: your-email@domain.com
description: A wonderful site
twitter_username: hffschmdt
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
show_drafts: true
