name:         rupert.xyz
description:  Rupert's life, reflections, business, ideas, failures, questions and lots more.
url:          http://rupert.xyz

plugins:
  - jekyll-seo-tag

permalink: /:title/
